
// Generated 2023年1月17日 下午11:23:43 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.msg.model;

import java.time.LocalDateTime;
import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import com.g.commons.model.AbstractEntity;

/**
 * SysMessageRecipient generated by hbm2java
 */
@Entity
@Table(name = "sys_message_recipient")
@DynamicInsert
@DynamicUpdate
public class SysMessageRecipient extends AbstractEntity implements java.io.Serializable {

    private Long id;
    private Long messageId;
    private Long recipientId;
    private String recipientName;
    private MessageTag tag;
    private LocalDateTime rtime;
    private Byte delFlag;

    public SysMessageRecipient() {
    }

    public SysMessageRecipient(Long id, Long messageId, Long recipientId, String recipientName) {
        this.id = id;
        this.messageId = messageId;
        this.recipientId = recipientId;
        this.recipientName = recipientName;
    }

    public SysMessageRecipient(Long id, Long messageId, Long recipientId, String recipientName, MessageTag tag, LocalDateTime rtime, Byte delFlag) {
        this.id = id;
        this.messageId = messageId;
        this.recipientId = recipientId;
        this.recipientName = recipientName;
        this.tag = tag;
        this.rtime = rtime;
        this.delFlag = delFlag;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(
            generator = "snowflake_generator"
    )
    @GenericGenerator(
            name = "snowflake_generator",
            strategy = "com.g.commons.utils.HibernateSnowflakeGenerator"
    )
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "message_id", nullable = false)
    public Long getMessageId() {
        return this.messageId;
    }

    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    @Column(name = "recipient_id", nullable = false)
    public Long getRecipientId() {
        return this.recipientId;
    }

    public void setRecipientId(Long recipientId) {
        this.recipientId = recipientId;
    }

    @Column(name = "recipient_name", nullable = false, length = 50)
    public String getRecipientName() {
        return this.recipientName;
    }

    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    @Column(name = "tag")
    @Enumerated(EnumType.STRING)
    public MessageTag getTag() {
        return this.tag;
    }

    public void setTag(MessageTag tag) {
        this.tag = tag;
    }

    @Column(name = "rtime", length = 19)
    public LocalDateTime getRtime() {
        return this.rtime;
    }

    public void setRtime(LocalDateTime rtime) {
        this.rtime = rtime;
    }

    @Column(name = "del_flag")
    public Byte getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SysMessageRecipient that = (SysMessageRecipient) o;

        if (!messageId.equals(that.messageId)) return false;
        return recipientId.equals(that.recipientId);
    }

    @Override
    public int hashCode() {
        int result = messageId.hashCode();
        result = 31 * result + recipientId.hashCode();
        return result;
    }
}


