<!doctype html>
<html lang="zh">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1">
    <base href="./"/>

    <title>Starter - G.Next Admin</title>

    <!-- include common vendor stylesheets & fontawesome -->
    <link rel="stylesheet" type="text/css" href="./vendors/bootstrap/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="./vendors/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="./vendors/fontawesome/css/regular.min.css">
    <link rel="stylesheet" type="text/css" href="./vendors/fontawesome/css/brands.min.css">
    <link rel="stylesheet" type="text/css" href="./vendors/fontawesome/css/solid.min.css">

    <!-- include fonts -->
    <link rel="stylesheet" type="text/css" href="./vendors/opensans/css">

    <!-- ace.css -->
    <link rel="stylesheet" type="text/css" href="./vendors/ace/ace.min.css">

    <!-- favicon -->
    <link rel="icon" type="image/png" href="./img/favicon.png"/>

    <!-- "Starter" page styles, specific to this page for demo only -->
</head>

<body>
<div class="body-container">
    <!-- Navbar -->
    <nav class="navbar navbar-sm navbar-expand-lg navbar-fixed navbar-blue">
        <div class="navbar-inner brc-grey-l2 shadow-md">
            <div class="d-flex h-100 align-items-center justify-content-xl-between">
                <a class="navbar-brand ml-2 text-white p-25" href="#">
                    <i class="fa fa-leaf"></i>
                    G.Next
                </a>
            </div>
        </div><!-- .navbar-inner -->
    </nav>

    <div class="main-container bgc-white">
        <!-- Main Content -->
        <div class="main-content">
            <!-- Page Content -->
            <div class="page-content container container-plus">
                <div class="row justify-content-center pos-rel">
                    <div class="pos-rel col-12 col-sm-7 mt-1 mt-sm-3">
                        <div class="py-3 px-1 py-lg-4 px-lg-5">
                            <div class="text-center fa-4x">
                                <span class="text-100 text-dark-m3 d-sm-none"><!-- smaller text to fit in small devices -->
                                    ¯\_(ツ)_/¯
                                </span>
                                <span class="text-110 text-dark-m3 d-none d-sm-inline">
                                    ¯\_(ツ)_/¯
                                </span>
                            </div>

                            <div class="text-center fa-4x text-orange-d2 letter-spacing-4">
                                403
                            </div>

                            <div class="text-center">
                                <span class="text-150 text-primary-d2">
                                    O!
                                </span>
                                <span class="text-120 text-primary-d2 p-15">
                                    您没有权限访问此页面，请联系管理员...
                                </span>
                            </div>

                            <hr class="border-double border-t-3 brc-secondary-l2 my-4">

                            <div class="text-center mt-4">
                                <a href="javascript:history.back()" class="btn btn-bgc-white btn-outline-default px-35 btn-text-slide-x">
                                    <i class="btn-text-2 fa fa-arrow-left text-110 align-text-bottom mr-2"></i>
                                    返回
                                </a>

                                <a href="" class="btn btn-bgc-white btn-outline-primary px-35">
                                    <i class="fa fa-home"></i>
                                    首页
                                </a>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- include common vendor scripts used in demo pages -->
<script src="./vendors/jquery/jquery.min.js"></script>
<script src="./vendors/popper/popper.min.js"></script>
<script src="./vendors/bootstrap/bootstrap.min.js"></script>

<!-- include ace.js -->
<script src="./vendors/ace/ace.min.js"></script>

</body>

</html>