// Generated 2022年12月10日 下午10:05:02 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.att.model;

import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import com.g.commons.model.AbstractEntity;

/**
 * SysAttachment generated by hbm2java
 */
@Entity
@Table(name = "sys_attachment")
@DynamicInsert
@DynamicUpdate
public class SysAttachment extends AbstractEntity implements java.io.Serializable {

    private Long id;
    private Module module;
    private String srcRecode;
    private String path;

    public SysAttachment() {
    }

    public SysAttachment(Long id, Module module, String srcRecode, String path) {
        this.id = id;
        this.module = module;
        this.srcRecode = srcRecode;
        this.path = path;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(
            generator = "snowflake_generator"
    )
    @GenericGenerator(
            name = "snowflake_generator",
            strategy = "com.g.commons.utils.HibernateSnowflakeGenerator"
    )
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "module", nullable = false, length = 30)
    @Enumerated(EnumType.STRING)
    public Module getModule() {
        return this.module;
    }

    public void setModule(Module module) {
        this.module = module;
    }

    @Column(name = "src_recode", nullable = false, length = 40)
    public String getSrcRecode() {
        return this.srcRecode;
    }

    public void setSrcRecode(String srcRecode) {
        this.srcRecode = srcRecode;
    }

    @Column(name = "path", nullable = false, length = 200)
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }


}


