// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import java.util.Objects;
import java.util.StringJoiner;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import com.g.commons.enums.Status;
import com.g.commons.model.AbstractEntity;

/**
 * SysAction generated by hbm2java
 */
@Entity
@Table(name = "sys_action")
@DynamicInsert
@DynamicUpdate
public class SysAction extends AbstractEntity implements java.io.Serializable {

    private Long id;
    private String resource;
    private ActionMethod method;
    private String description;
    private Status status;

    public SysAction() {
    }

    public SysAction(Long id) {
        this.id = id;
    }

    public SysAction(String id) {
        this.id = Long.valueOf(id);
    }

    public SysAction(Long id, String resource, ActionMethod method, String description, Status status) {
        this.id = id;
        this.resource = resource;
        this.method = method;
        this.description = description;
        this.status = status;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(
            generator = "snowflake_generator"
    )
    @GenericGenerator(
            name = "snowflake_generator",
            strategy = "com.g.commons.utils.HibernateSnowflakeGenerator"
    )
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "resource", nullable = false, length = 255)
    @NotEmpty
    public String getResource() {
        return this.resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }

    @Column(name = "method", nullable = false)
    @NotNull
    @Enumerated(EnumType.STRING)
    public ActionMethod getMethod() {
        return this.method;
    }

    public void setMethod(ActionMethod method) {
        this.method = method;
    }

    @Column(name = "description", nullable = true, length = 255)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SysAction sysAction = (SysAction) o;
        return Objects.equals(id, sysAction.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return new StringJoiner(", ", SysAction.class.getSimpleName() + "[", "]")
                .add("id=" + id)
                .add("resource='" + resource + "'")
                .add("method=" + method)
                .add("description='" + description + "'")
                .add("status=" + status)
                .toString();
    }
}


