// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import javax.persistence.*;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import com.g.commons.enums.Status;
import com.g.commons.model.AbstractEntity;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name = "sys_menu")
@DynamicInsert
@DynamicUpdate
public class SysMenu extends AbstractEntity implements java.io.Serializable {

    private Long id;
    private Long parentId;
    private String label;
    private String title;
    private String icon;
    private String url;
    private Integer order;
    private Status status;

    public SysMenu() {
    }

    public SysMenu(Long id, Long parentId, String label, Status status) {
        this.id = id;
        this.parentId = parentId;
        this.label = label;
        this.status = status;
    }

    public SysMenu(Long id, Long parentId, String label, String title, String icon, String url, Integer order, Status status) {
        this.id = id;
        this.parentId = parentId;
        this.label = label;
        this.title = title;
        this.icon = icon;
        this.url = url;
        this.order = order;
        this.status = status;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(
            generator = "snowflake_generator"
    )
    @GenericGenerator(
            name = "snowflake_generator",
            strategy = "com.g.commons.utils.HibernateSnowflakeGenerator"
    )
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "parent_id", nullable = false)
    @NotNull
    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Column(name = "label", nullable = false, length = 30)
    @NotEmpty
    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Column(name = "title", length = 60)
    @NotEmpty
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "icon", length = 255)
    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Column(name = "url", length = 255)
    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "\"order\"")
    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    public Status getStatus() {
        return this.status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

}


