// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import java.time.LocalDateTime;

import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonIgnore;

import com.g.commons.model.AbstractEntity;

/**
 * SysPersistentLogins generated by hbm2java
 */
@Entity
@Table(name = "sys_persistent_logins")
@DynamicInsert
@DynamicUpdate
public class SysPersistentLogin extends AbstractEntity implements java.io.Serializable {

    private String series;
    private Long uid;
    private String token;
    private LocalDateTime lastUsed;

    public SysPersistentLogin() {
    }

    public SysPersistentLogin(String series, LocalDateTime lastUsed) {
        this.series = series;
        this.lastUsed = lastUsed;
    }

    public SysPersistentLogin(String series, Long uid, String token, LocalDateTime lastUsed) {
        this.series = series;
        this.uid = uid;
        this.token = token;
        this.lastUsed = lastUsed;
    }

    @Id
    @Column(name = "series", unique = true, nullable = false, length = 64)
    public String getSeries() {
        return this.series;
    }

    public void setSeries(String series) {
        this.series = series;
    }

    @Column(name = "uid")
    public Long getUid() {
        return this.uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    @Column(name = "token", length = 64)
    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Column(name = "last_used", nullable = false, length = 19)
    public LocalDateTime getLastUsed() {
        return this.lastUsed;
    }

    public void setLastUsed(LocalDateTime lastUsed) {
        this.lastUsed = lastUsed;
    }

    @Override
    @Transient
    @JsonIgnore
    public String getId() {
        return this.series;
    }

}


