// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRoleMembersId generated by hbm2java
 */
@Embeddable
public class SysRoleMembersId implements java.io.Serializable {

    private Long userId;
    private Long roleId;

    public SysRoleMembersId() {
    }

    public SysRoleMembersId(Long userId, Long roleId) {
        this.userId = userId;
        this.roleId = roleId;
    }


    @Column(name = "user_id", nullable = false)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Column(name = "role_id", nullable = false)
    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof SysRoleMembersId)) return false;
        SysRoleMembersId castOther = (SysRoleMembersId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
                && ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null && castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
        return result;
    }


}


