// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SysRoleAuthoritiesId generated by hbm2java
 */
@Embeddable
public class SysRoleAuthoritiesId implements java.io.Serializable {

    private Long roleId;
    private String authority;

    public SysRoleAuthoritiesId() {
    }

    public SysRoleAuthoritiesId(Long roleId, String authority) {
        this.roleId = roleId;
        this.authority = authority;
    }


    @Column(name = "role_id", nullable = false)
    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    @Column(name = "authority", nullable = false, length = 50)
    public String getAuthority() {
        return this.authority;
    }

    public void setAuthority(String authority) {
        this.authority = authority;
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof SysRoleAuthoritiesId)) return false;
        SysRoleAuthoritiesId castOther = (SysRoleAuthoritiesId) other;

        return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null && castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
                && ((this.getAuthority() == castOther.getAuthority()) || (this.getAuthority() != null && castOther.getAuthority() != null && this.getAuthority().equals(castOther.getAuthority())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
        result = 37 * result + (getAuthority() == null ? 0 : this.getAuthority().hashCode());
        return result;
    }


}


