// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.g.commons.model.AbstractEntity;

/**
 * SysRoleAuthorities generated by hbm2java
 */
@Entity
@Table(name = "sys_role_authorities")
@DynamicInsert
@DynamicUpdate
public class SysRoleAuthorities extends AbstractEntity implements java.io.Serializable {

    private SysRoleAuthoritiesId id;

    public SysRoleAuthorities() {
    }

    public SysRoleAuthorities(SysRoleAuthoritiesId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
            @AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 50))})
    public SysRoleAuthoritiesId getId() {
        return this.id;
    }

    public void setId(SysRoleAuthoritiesId id) {
        this.id = id;
    }


}


