// Generated 2021年1月19日 上午11:12:12 by Hibernate Tools 6.0.0.Alpha2

package com.g.sys.sec.model;

import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.g.commons.model.AbstractEntity;

/**
 * SysUserAuthorities generated by hbm2java
 */
@Entity
@Table(name = "sys_user_authorities")
@DynamicInsert
@DynamicUpdate
public class SysUserAuthorities extends AbstractEntity implements java.io.Serializable {

    private SysUserAuthoritiesId id;

    public SysUserAuthorities() {
    }

    public SysUserAuthorities(SysUserAuthoritiesId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "uid", column = @Column(name = "uid", nullable = false)),
            @AttributeOverride(name = "authority", column = @Column(name = "authority", nullable = false, length = 50))})
    public SysUserAuthoritiesId getId() {
        return this.id;
    }

    public void setId(SysUserAuthoritiesId id) {
        this.id = id;
    }


}


