server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    com:
      g: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        engine:
          QueryParameters: TRACE
          HQLQueryPlan: TRACE
        type:
          descriptor:
            sql: TRACE
        cache: TRACE

spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  jmx:
    enabled: true
  redis:
    host: 39.105.19.141
    port: 7001
    password: 9vrGKspASS
    database: 0
    connect-timeout: 60000
    timeout: 10000
  # 配置数据源信息
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.19.141:3306/next?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: hmFFXag3Ek
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: jcache
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
  freemarker:
    template-loader-path: "classpath:/templates/"
    charset: "UTF-8"
    suffix: ".html"
    cache: false
    content-type: "text/html"
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true


# Actuator
#management:
#  endpoints:
#    enabled-by-default: true
#    jmx:
#      exposure:
#        include: "*"
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    httptrace:
#      enabled: true
#    info:
#      enabled: true
#  trace:
#    http:
#      include: true

g:
  commons:
    IDGenerator:
      datacenterId: 0
      workerId: 0
    HexIDGenerator:
      workerId: '00'
  sec:
    entryPoint:
      realmName: "G.Next Open Api"
    jwtService:
      secret: "CbQNsCSmYrJ1"
      issuer: "G.Next"
      duration: 1800 # 30min