server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: INFO
    com:
      g: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        engine:
          QueryParameters: TRACE
          HQLQueryPlan: TRACE
        type:
          descriptor:
            sql: TRACE
        cache: TRACE

spring:
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  # 配置数据源信息
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_db?serverTimezone=UTC&characterEncoding=utf-8
    username: db_user
    password: 123456
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            entity:
              expiration:
                time_to_live: 86400000 # milliseconds
                max_idle_time: 3600000 # milliseconds
            collection:
              expiration:
                time_to_live: 86400000
                max_idle_time: 3600000
            naturalid:
              expiration:
                time_to_live: 86400000
                max_idle_time: 3600000
            query:
              expiration:
                time_to_live: 86400000
                max_idle_time: 3600000
            timestamps:
              expiration:
                time_to_live: 86400000
                max_idle_time: 3600000

# Actuator
management:
  endpoint:
    httptrace:
      enabled: true
  trace:
    http:
      include: true
  endpoints:
    web:
      exposure:
        include: "*"

g:
  commons:
    IDGenerator:
      datacenterId: 0
      workerId: 0
    HexIDGenerator:
      workerId: '00'
  sec:
    entryPoint:
      realmName: "G.Next Open Api"
    jwtService:
      secret: "CbQNsCSmYrJ1"
      issuer: "G.Next"
      duration: 1800 # 30min