// Generated 2022年12月10日 下午10:08:51 by Hibernate Tools 6.0.0.Alpha2

package com.g.bbs.model;

import javax.persistence.*;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import com.g.commons.model.AbstractEntity;

/**
 * BbsColumn generated by hbm2java
 */
@Entity
@Table(name = "bbs_column")
@DynamicInsert
@DynamicUpdate
@Cacheable
public class BbsColumn extends AbstractEntity implements java.io.Serializable {
    private Long id;
    private String name;
    private Long parentId;
    private String parentName;
    private String icon;
    private Integer sort;
    private String status;

    public BbsColumn() {
    }

    public BbsColumn(String name, String status) {
        this.name = name;
        this.status = status;
    }

    public BbsColumn(String name, Long parentId, String icon, Integer sort, String status) {
        this.name = name;
        this.parentId = parentId;
        this.icon = icon;
        this.sort = sort;
        this.status = status;
    }

    @Id
    @GeneratedValue(
            generator = "snowflake_generator"
    )
    @GenericGenerator(
            name = "snowflake_generator",
            strategy = "com.g.commons.utils.HibernateSnowflakeGenerator"
    )
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name", nullable = false, length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "parent_id", nullable = false)
    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Transient
    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    @Column(name = "icon", length = 200)
    public String getIcon() {
        return this.icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Column(name = "sort")
    public Integer getSort() {
        return this.sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @Column(name = "status", nullable = false, length = 7)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}


